name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          
      - name: Compile Windows (x64)
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -o AstroSession-Creator_windows_x64.exe .

      - name: Compile Linux (x64)
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o AstroSession-Creator_linux_x64 .

      - name: Compile macOS (Intel)
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -o AstroSession-Creator_mac_intel .
        
      - name: Auto-Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          make_latest: true
          files: |
            AstroSession-Creator_windows_x64.exe
            AstroSession-Creator_linux_x64
            AstroSession-Creator_mac_intel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
